package com.cpo.timing.timingproject;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "DisputeObject")
public class DisputeObject  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "accountNumber")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String accountNumber;
    
    @org.kie.api.definition.type.Label(value = "approvalRequired")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Boolean approvalRequired;
    
    @org.kie.api.definition.type.Label(value = "approved")
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.Boolean approved;
    
    @org.kie.api.definition.type.Label(value = "disputeDate")
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.Date disputeDate;
    
    @org.kie.api.definition.type.Label(value = "disputeId")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Short disputeId;
    
    @org.kie.api.definition.type.Label(value = "disputeNotes")
    @org.kie.api.definition.type.Position(value = 10)
    private java.lang.String disputeNotes;
    
    @org.kie.api.definition.type.Label(value = "disputedAmount")
    @org.kie.api.definition.type.Position(value = 5)
    private java.math.BigDecimal disputedAmount;
    
    @org.kie.api.definition.type.Label(value = "researchRequired")
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.Boolean researchRequired;
    
    @org.kie.api.definition.type.Label(value = "resolutionDate")
    @org.kie.api.definition.type.Position(value = 9)
    private java.util.Date resolutionDate;
    
    @org.kie.api.definition.type.Label(value = "transactionDate")
    @org.kie.api.definition.type.Position(value = 3)
    private java.util.Date transactionDate;
    
    @org.kie.api.definition.type.Label(value = "vendorName")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String vendorName;

    public DisputeObject() {
    }

    public DisputeObject(java.lang.Short disputeId, java.util.Date disputeDate, java.lang.String accountNumber, java.util.Date transactionDate, java.lang.String vendorName, java.math.BigDecimal disputedAmount, java.lang.Boolean approvalRequired, java.lang.Boolean researchRequired, java.lang.Boolean approved, java.util.Date resolutionDate, java.lang.String disputeNotes) {
        this.disputeId = disputeId;
        this.disputeDate = disputeDate;
        this.accountNumber = accountNumber;
        this.transactionDate = transactionDate;
        this.vendorName = vendorName;
        this.disputedAmount = disputedAmount;
        this.approvalRequired = approvalRequired;
        this.researchRequired = researchRequired;
        this.approved = approved;
        this.resolutionDate = resolutionDate;
        this.disputeNotes = disputeNotes;
    }


    
    public java.lang.String getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(  java.lang.String accountNumber ) {
        this.accountNumber = accountNumber;
    }
    
    public java.lang.Boolean getApprovalRequired() {
        return this.approvalRequired;
    }

    public void setApprovalRequired(  java.lang.Boolean approvalRequired ) {
        this.approvalRequired = approvalRequired;
    }
    
    public java.lang.Boolean getApproved() {
        return this.approved;
    }

    public void setApproved(  java.lang.Boolean approved ) {
        this.approved = approved;
    }
    
    public java.util.Date getDisputeDate() {
        return this.disputeDate;
    }

    public void setDisputeDate(  java.util.Date disputeDate ) {
        this.disputeDate = disputeDate;
    }
    
    public java.lang.Short getDisputeId() {
        return this.disputeId;
    }

    public void setDisputeId(  java.lang.Short disputeId ) {
        this.disputeId = disputeId;
    }
    
    public java.lang.String getDisputeNotes() {
        return this.disputeNotes;
    }

    public void setDisputeNotes(  java.lang.String disputeNotes ) {
        this.disputeNotes = disputeNotes;
    }
    
    public java.math.BigDecimal getDisputedAmount() {
        return this.disputedAmount;
    }

    public void setDisputedAmount(  java.math.BigDecimal disputedAmount ) {
        this.disputedAmount = disputedAmount;
    }
    
    public java.lang.Boolean getResearchRequired() {
        return this.researchRequired;
    }

    public void setResearchRequired(  java.lang.Boolean researchRequired ) {
        this.researchRequired = researchRequired;
    }
    
    public java.util.Date getResolutionDate() {
        return this.resolutionDate;
    }

    public void setResolutionDate(  java.util.Date resolutionDate ) {
        this.resolutionDate = resolutionDate;
    }
    
    public java.util.Date getTransactionDate() {
        return this.transactionDate;
    }

    public void setTransactionDate(  java.util.Date transactionDate ) {
        this.transactionDate = transactionDate;
    }
    
    public java.lang.String getVendorName() {
        return this.vendorName;
    }

    public void setVendorName(  java.lang.String vendorName ) {
        this.vendorName = vendorName;
    }
}